import { getRedis } from "../redis.ts";
import { prisma } from "../db.ts";
import { log } from "./logger.ts";
import { publishToUser } from "./events.ts";
import { Prisma } from "@mokara/db/prisma/generated/client";

// PRD-05: the notification service. Rows live in Postgres (survive devices,
// backfill the drawer on load); each insert is also published to the user's
// Redis channel so connected SSE clients see it instantly.
//
// The payload is whatever the row needs to render + link; the drawer reads
// optional fields off it, so new kinds never need a migration. Types are
// plain strings (see the schema comment). Payload shape by type:
//   invitation          { actor_username, team_name, team_id, invitation_id,
//                          responded? } — responded is set when the invitee
//                          acts, turning the row's buttons into a state chip
//   invitation_accepted { actor_username, team_name, team_id }
//   comment_reply       { actor_username, task_id, task_title, team_id, snippet }
// (due-date reminders are documented phase 2 — they need a scheduler).

// Best-effort delivery: a notification that cannot be written or published
// must never take down the action that generated it (an invite, a reply) —
// log and return.
export async function notify(
  userId: string,
  type: string,
  payload: Prisma.InputJsonValue
): Promise<void> {
  try {
    const row = await prisma.notification.create({
      data: { userId, type, payload },
    });
    await publishToUser(userId, {
      event: "notification",
      data: {
        id: row.id,
        type: row.type,
        payload: row.payload,
        read_at: row.readAt,
        created_at: row.createdAt.toISOString(),
      },
    });
  } catch (e) {
    log.error(`could not notify user ${userId} (${type})`, e);
  }
}

// Marks notifications read. `ids: null` means every unread one (the drawer's
// "mark all"); an empty array is a no-op, not "everything".
export async function markRead(userId: string, ids: string[] | null): Promise<number> {
  const res = await prisma.notification.updateMany({
    where: { userId, readAt: null, ...(ids ? { id: { in: ids } } : {}) },
    data: { readAt: new Date() },
  });
  return res.count;
}

// PRD-11 §1.5 → notification feed: per-user "due soon" rows. The Phase 1.5
// banner was a GET that re-computed the set on every page load; the same set
// is now persisted as one row per matching task so the bell badge + drawer
// can render it through the same notification surface. No scheduler, no email —
// the rows are regenerated by the mutation hooks (createTask, PATCH due/status
// /assignee, DELETE, accept-invite) and once per session-start on GET
// /notifications. Same 48h horizon and the same done/canceled exclusion as the
// old banner; persistence replaces the per-tab dismiss (mark-read semantics,
// same as task_assigned / comment_reply).
//   payload = { task_id, task_title, team_id, team_name, due_date, overdue }

type DueSoonTask = {
  id: string;
  title: string;
  // The where-clause filters out null dueDates; Prisma's return type still
  // includes the union, so we type it loosely and assert at use time.
  dueDate: Date | null;
  teamId: string;
  team: { name: string } | null;
};

/** 48h wall-clock horizon, matched against the stored timestamp. */
const DUE_SOON_HORIZON_MS = 48 * 60 * 60 * 1000;

/**
 * Tasks currently in the user's "due soon" attention set. `scope` keeps one
 * query reusable: pass a team to limit, leave it undefined for "every team
 * the user belongs to" (the per-user catch-up path).
 */
async function dueSoonMatchingTasks(scope: {
  userId?: string;
  teamId?: string;
}): Promise<DueSoonTask[]> {
  const horizon = new Date(Date.now() + DUE_SOON_HORIZON_MS);
  let teamIds: string[] | undefined;
  if (scope.teamId) {
    teamIds = [scope.teamId];
  } else if (scope.userId) {
    const memberships = await prisma.teamMember.findMany({
      where: { userId: scope.userId },
      select: { teamId: true },
    });
    teamIds = memberships.map((m) => m.teamId);
    if (teamIds.length === 0) return [];
  }
  return prisma.task.findMany({
    where: {
      ...(teamIds ? { teamId: { in: teamIds } } : {}),
      dueDate: { not: null, lte: horizon },
      // Finished tasks are not coming due — the same exclusion as the old
      // banner; this is what makes the set an attention list, not a date dump.
      status: { notIn: ["done", "canceled"] },
    },
    orderBy: { dueDate: "asc" },
    select: {
      id: true,
      title: true,
      dueDate: true,
      teamId: true,
      team: { select: { name: true } },
    },
  });
}

/**
 * Build the wire payload for a due-soon row. `overdue` is computed at write
 * time. `dueDate` is asserted non-null because the matching query's
 * `where: { dueDate: { not: null, ... } }` guarantees it — but Prisma's
 * generated row type still reports `Date | null`, so the local type mirrors
 * that and this helper narrows it once at the boundary.
 */
function dueSoonPayload(task: DueSoonTask): Prisma.InputJsonValue {
  if (!task.dueDate) throw new Error(`due-soon row ${task.id} has no dueDate`);
  const due = task.dueDate.getTime();
  return {
    task_id: task.id,
    task_title: task.title,
    team_id: task.teamId,
    team_name: task.team?.name ?? null,
    due_date: task.dueDate.toISOString(),
    overdue: due < Date.now(),
  };
}

/**
 * Brings the user's due-soon rows in line with the current matching set.
 *   - Deletes rows whose task no longer matches (done / canceled / date moved
 *     out of the 48h window / task deleted / user removed from the container).
 *   - Inserts rows for matching tasks that have no row yet, and publishes each
 *     one over SSE so the bell badge + drawer update without a refetch.
 *   - Leaves already-matching rows alone — that preserves the user's mark-read
 *     state across regenerations (the same row stays read; a re-entering task
 *     rightly gets a fresh unread row because its previous row was deleted
 *     when it left the window).
 *
 * `matchingTasks` lets the per-team path pre-fetch the set once and reuse it
 * for every member. Omitted on the per-user catch-up path, which reads the
 * user's full membership set in one query.
 */
export async function regenerateDueSoonForUser(
  userId: string,
  matchingTasks?: DueSoonTask[]
): Promise<void> {
  try {
    const tasks = matchingTasks ?? (await dueSoonMatchingTasks({ userId }));
    const existing = await prisma.notification.findMany({
      where: { userId, type: "due_soon" },
      select: { id: true, payload: true },
    });

    const matchingIds = new Set(tasks.map((t) => t.id));
    const staleIds = existing
      .filter((r) => {
        const pid = (r.payload as { task_id?: string } | null)?.task_id;
        return !pid || !matchingIds.has(pid);
      })
      .map((r) => r.id);
    if (staleIds.length > 0) {
      await prisma.notification.deleteMany({ where: { id: { in: staleIds } } });
    }

    const existingTaskIds = new Set(
      existing
        .map((r) => (r.payload as { task_id?: string } | null)?.task_id)
        .filter((id): id is string => Boolean(id))
    );
    for (const task of tasks) {
      if (existingTaskIds.has(task.id)) continue;
      const row = await prisma.notification.create({
        data: { userId, type: "due_soon", payload: dueSoonPayload(task) },
      });
      await publishToUser(userId, {
        event: "notification",
        data: {
          id: row.id,
          type: row.type,
          payload: row.payload,
          read_at: row.readAt,
          created_at: row.createdAt.toISOString(),
        },
      });
    }
  } catch (e) {
    // Same posture as notify(): a regeneration miss must never take down the
    // mutation that triggered it. The next regen (next mutation, next page
    // load, accept-invite catch-up) will pick up where this left off.
    log.error(`could not regenerate due-soon for user ${userId}`, e);
  }
}

/**
 * Per-team regeneration — one matchingTasks query, N member regenerations.
 * Called from every mutation that could change a team's due-soon set
 * (createTask, PATCH due_date / status / assignee, DELETE).
 */
export async function regenerateDueSoonForTeam(teamId: string): Promise<void> {
  try {
    const [members, tasks] = await Promise.all([
      prisma.teamMember.findMany({ where: { teamId }, select: { userId: true } }),
      dueSoonMatchingTasks({ teamId }),
    ]);
    for (const { userId } of members) {
      await regenerateDueSoonForUser(userId, tasks);
    }
  } catch (e) {
    log.error(`could not regenerate due-soon for team ${teamId}`, e);
  }
}

// PRD-08's flow responder, PRD-05's bookkeeper: when the invitee accepts or
// declines, their invitation notification's payload gains `responded` (so the
// drawer swaps its buttons for a state chip on every device), the row is
// read-marked, and the updated row is republished over SSE. Best-effort, like
// notify.
export async function markInvitationResponded(
  userId: string,
  invitationId: string,
  outcome: "accepted" | "declined"
): Promise<void> {
  try {
    const row = await prisma.notification.findFirst({
      where: {
        userId,
        type: "invitation",
        payload: { path: ["invitation_id"], equals: invitationId },
      },
      orderBy: { createdAt: "desc" },
    });
    if (!row) return;
    const old = row.payload;
    const payload =
      typeof old === "object" && old !== null && !Array.isArray(old)
        ? { ...old, responded: outcome }
        : { responded: outcome };
    const updated = await prisma.notification.update({
      where: { id: row.id },
      data: { payload, readAt: row.readAt ?? new Date() },
    });
    await publishToUser(userId, {
      event: "notification",
      data: {
        id: updated.id,
        type: updated.type,
        payload: updated.payload,
        read_at: updated.readAt,
        created_at: updated.createdAt.toISOString(),
      },
    });
  } catch (e) {
    log.error(`could not mark invitation ${invitationId} responded for user ${userId}`, e);
  }
}
